### ISSUE TITLE
Margin around text - fullwidth template 

### ISSUE THREAD

**Issue by jvsingh** [jksikhs/cms.jksikhs.com#18]
There needs to be some margin built in to the template. 
Compare how text areas render in live (older css version) versus test (new)

Issue seen on both mobile & desktop 

![32244DDA-976F-40AE-B867-B0CD31D90387](https://user-images.githubusercontent.com/6246002/85045756-52701580-b187-11ea-85e9-1707daff01c1.jpeg)
![CA60E1C2-16B0-43D0-AF2A-7BBF14C42DF4](https://user-images.githubusercontent.com/6246002/85045765-556b0600-b187-11ea-822e-e458feba44a5.jpeg)

**Comment by devgurjeet** [comment]
you can add class **section-space** on containers.
