### ISSUE TITLE
djangocms_blog content rendering with new templates 

### ISSUE THREAD

**Issue by jvsingh** [jksikhs/cms.jksikhs.com#25]
Blog listing and content has rendering issues with new template. Compare new & legacy in screenshots 
New one doesn’t show adequate margins (the only issue is in displaying blog content. Other pages render fine with the new templates)

![A05272AA-7767-4D5C-A174-088FA7644444](https://user-images.githubusercontent.com/6246002/85808068-b7a9a500-b74b-11ea-9e8a-665c10e16f52.jpeg)
![956BD25F-A958-4A9F-9B3B-8A37B0FEFBFA](https://user-images.githubusercontent.com/6246002/85808072-bb3d2c00-b74b-11ea-8716-8c9b288934f3.jpeg)

**Comment by jksikhs** [comment]
Leaving it open in case there are other improvements needed
